openapi: 3.0.0
info:
  title: 'HRIS Payroll API - User'
  version: 0.1.16
servers:
  -
    url: 'http://localhost:8088/api/'
    description: URI
components:
  parameters:
    acceptsJson:
      name: Accept
      in: header
      required: true
      schema:
        type: string
        example: application/json
        default: application/json
  examples:
    dummyuser:
      summary: 'Dummy username and password'
      value:
        username: dummyuser
        password: secret
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
tags:
  -
    name: user
    description: 'Everything about User API'
paths:
  /user/create:
    post:
      summary: 'create record'
      tags:
        - user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                email:
                  type: string
                password:
                  type: string
                isActive:
                  type: boolean
                role:
                  type: string
                permissions:
                  type: array
              required:
                - username
                - email
                - password
                - isActive
                - role
                - permissions
      security:
        -
          bearerAuth: {  }
      parameters:
        -
          $ref: '#/components/parameters/acceptsJson'
      responses:
        '"201"':
          description: 'User created message'
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 'user successfully created.'
        '"401"':
          description: 'Bearer token not authorized'
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Unauthenticated
  '/user/search/{id}':
    get:
      summary: 'get record'
      tags:
        - user
      security:
        -
          bearerAuth: {  }
      parameters:
        -
          $ref: '#/components/parameters/acceptsJson'
        -
          in: path
          name: id
          required: false
          schema:
            type: integer
          description: 'primary key'
        -
          in: query
          name: searchValue
          schema:
            type: string
          description: 'search value'
        -
          in: query
          name: hasEmployee
          schema:
            type: boolean
          description: 'check record has employee record'
        -
          in: query
          name: page
          schema:
            type: integer
          description: 'for pagination'
        -
          in: query
          name: perPage
          schema:
            type: integer
          description: 'for pagination'
        -
          in: query
          name: field
          schema:
            type: string
          description: 'for sorting'
        -
          in: query
          name: order
          schema:
            type: string
            enum:
              - ASC
              - DESC
          description: 'for sorting'
      responses:
        '"200"':
          description: 'return User records'
          content:
            application/json:
              schema:
                type: array
                example:
                  -
                    id: 1
                    username: string
                    email: string
                    password: string
                    isActive: boolean
                    shouldChange: boolean
                    created_at: '2021-01-27 10:46:10'
                    updated_at: '2021-01-27 10:46:10'
                  -
                    id: 1
                    username: string
                    email: string
                    password: string
                    isActive: boolean
                    shouldChange: boolean
                    created_at: '2021-01-27 10:46:10'
                    updated_at: '2021-01-27 10:46:10'
        '"401"':
          description: 'Bearer token not authorized'
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Unauthenticated
  '/user/update/{id}':
    put:
      summary: 'update record'
      tags:
        - user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                email:
                  type: string
                password:
                  type: string
                isActive:
                  type: boolean
                role:
                  type: string
                permissions:
                  type: array
              required:
                - username
                - email
                - isActive
                - role
                - permissions
      security:
        -
          bearerAuth: {  }
      parameters:
        -
          $ref: '#/components/parameters/acceptsJson'
        -
          in: path
          name: id
          required: true
          schema:
            type: integer
          description: 'primary key'
      responses:
        '"204"':
          description: 'User update message'
          content: null
        '"401"':
          description: 'Bearer token not authorized'
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Unauthenticated
  '/user/parameter':
    get:
      summary: 'get parameter'
      tags:
        - user
      security:
        -
          bearerAuth: {  }
      parameters:
        -
          $ref: '#/components/parameters/acceptsJson'
      responses:
        '"200"':
          description: 'return user parameter'
          content:
            application/json:
              schema:
                type: object
                example: {'sample' : [1,2,3]}
        '"401"':
          description: 'Bearer token not authorized'
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Unauthenticated
