openapi: 3.0.0
info:
  title: 'HRIS Payroll API - EmployeeSchedule'
  version: 0.2.3
servers:
  -
    url: 'http://localhost:8088/api/'
    description: URI
components:
  parameters:
    acceptsJson:
      name: Accept
      in: header
      required: true
      schema:
        type: string
        example: application/json
        default: application/json
  examples:
    dummyuser:
      summary: 'Dummy username and password'
      value:
        username: dummyuser
        password: secret
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
tags:
  -
    name: employeeschedule
    description: 'Everything about EmployeeSchedule API'
paths:
  /employee/schedule/create/{employeeId}:
    post:
      summary: 'create record'
      tags:
        - employeeschedule
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                schedule_type:
                  type: string
                  enum:
                    - REGULAR
                    - SPECIAL
                effective_date:
                  type: date
                schedule_id:
                  type: integer
                special_schedule_id:
                  type: integer
                type:
                  type: string
                  enum:
                    - PERMANENT
                    - ONE_TIME
              required:
                - schedule_type
                - effective_date
      security:
        -
          bearerAuth: {  }
      parameters:
        -
          $ref: '#/components/parameters/acceptsJson'
        -
          in: path
          name: employeeId
          required: true
          schema:
            type: integer
          description: 'Employee id'
      responses:
        '"201"':
          description: 'EmployeeSchedule created message'
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 'employee/schedule successfully created.'
        '"401"':
          description: 'Bearer token not authorized'
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Unauthenticated
  '/employee/schedule/search/{employeeId}':
    get:
      summary: 'get record'
      tags:
        - employeeschedule
      security:
        -
          bearerAuth: {  }
      parameters:
        -
          $ref: '#/components/parameters/acceptsJson'
        -
          in: path
          name: employeeId
          required: false
          schema:
            type: integer
          description: 'Employee id'
        -
          in: query
          name: searchValue
          schema:
            type: string
          description: 'search value'
        -
          in: query
          name: page
          schema:
            type: integer
          description: 'for pagination'
        -
          in: query
          name: perPage
          schema:
            type: integer
          description: 'for pagination'
        -
          in: query
          name: field
          schema:
            type: string
          description: 'for sorting'
        -
          in: query
          name: order
          schema:
            type: string
            enum:
              - ASC
              - DESC
          description: 'for sorting'
      responses:
        '"200"':
          description: 'return EmployeeSchedule records'
          content:
            application/json:
              schema:
                type: array
                example:
                  -
                    id: 1
                    schedule_id: relatedTo
                    employee_id: relatedTo
                    effective_date: date
                    created_at: '2021-02-01 21:39:48'
                    updated_at: '2021-02-01 21:39:48'
                  -
                    id: 1
                    schedule_id: relatedTo
                    employee_id: relatedTo
                    effective_date: date
                    created_at: '2021-02-01 21:39:48'
                    updated_at: '2021-02-01 21:39:48'
        '"401"':
          description: 'Bearer token not authorized'
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Unauthenticated
  '/employee/schedule/delete/{id}':
    delete:
      summary: 'delete record'
      tags:
        - employeeschedule
      security:
        -
          bearerAuth: {  }
      parameters:
        -
          $ref: '#/components/parameters/acceptsJson'
        -
          in: path
          name: id
          required: true
          schema:
            type: integer
          description: 'primary key'
      responses:
        '"204"':
          description: 'EmployeeSchedule delete message'
          content: null
        '"401"':
          description: 'Bearer token not authorized'
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Unauthenticated
  '/employee/schedule/search':
    get:
      summary: 'get employees list'
      tags:
        - employeeschedule
      security:
        -
          bearerAuth: {  }
      parameters:
        -
          $ref: '#/components/parameters/acceptsJson'
        -
          in: path
          name: id
          required: false
          schema:
            type: integer
          description: 'primary key'
        -
          in: path
          name: employeeId
          required: false
          schema:
            type: integer
          description: employee id
        -
          in: query
          name: searchValue
          schema:
            type: string
          description: 'search value'
        -
          in: query
          name: page
          schema:
            type: integer
          description: 'for pagination'
        -
          in: query
          name: perPage
          schema:
            type: integer
          description: 'for pagination'
        -
          in: query
          name: field
          schema:
            type: string
          description: 'for sorting'
        -
          in: query
          name: order
          schema:
            type: string
            enum:
              - ASC
              - DESC
          description: 'for sorting'
      responses:
        '"200"':
          description: 'return ServiceRecord records'
          content:
            application/json:
              schema:
                type: array
                example:
                  -
                    id: 1
                    first_name: sample
                    last_name: sample
                    middle_name: sample
                  
        '"401"':
          description: 'Bearer token not authorized'
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Unauthenticated
  /employee/schedule/today/{employeeId}:
    get:
      summary: 'get today'
      tags:
        - employeeschedule
      security:
        -
          bearerAuth: {  }
      parameters:
        -
          $ref: '#/components/parameters/acceptsJson'
        -
          in: path
          name: employeeId
          required: true
          schema:
            type: integer
          description: 'Employee id'
      responses:
        '"200"':
          description: 'return today schedule'
          content:
            application/json:
              schema:
                type: array
                example: ['sample' : []]
        '"401"':
          description: 'Bearer token not authorized'
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Unauthenticated
  /employee/schedule/parameter/:
    get:
      summary: 'get parameter'
      tags:
        - employeeschedule
      security:
        -
          bearerAuth: {  }
      parameters:
        -
          $ref: '#/components/parameters/acceptsJson'
      responses:
        '"200"':
          description: 'return parameters'
          content:
            application/json:
              schema:
                type: array
                example: ['sample' : []]
        '"401"':
          description: 'Bearer token not authorized'
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Unauthenticated
  /employee/schedule/special-schedule/parameter/:
    get:
      summary: 'get special schedule parameter'
      tags:
        - employeeschedule
      security:
        -
          bearerAuth: {  }
      parameters:
        -
          $ref: '#/components/parameters/acceptsJson'
        -
          in: query
          name: ref_date
          schema:
            type: date
          description: 'search by ref_date'
      responses:
        '"200"':
          description: 'return parameters'
          content:
            application/json:
              schema:
                type: array
                example: ['sample' : []]
        '"401"':
          description: 'Bearer token not authorized'
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Unauthenticated
  /employee/schedule/portal/search/:
    get:
      summary: 'get portal record'
      tags:
        - employeeschedule
      security:
        -
          bearerAuth: {  }
      parameters:
        -
          $ref: '#/components/parameters/acceptsJson'
      responses:
        '"200"':
          description: 'return EmployeeSchedule records'
          content:
            application/json:
              schema:
                type: array
                example:
                  -
                    id: 1
                    schedule_id: relatedTo
                    employee_id: relatedTo
                    effective_date: date
                    created_at: '2021-02-01 21:39:48'
                    updated_at: '2021-02-01 21:39:48'
                  -
                    id: 1
                    schedule_id: relatedTo
                    employee_id: relatedTo
                    effective_date: date
                    created_at: '2021-02-01 21:39:48'
                    updated_at: '2021-02-01 21:39:48'
        '"401"':
          description: 'Bearer token not authorized'
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Unauthenticated
  /employee/schedule/portal/today:
    get:
      summary: 'get portal today'
      tags:
        - employeeschedule
      security:
        -
          bearerAuth: {  }
      parameters:
        -
          $ref: '#/components/parameters/acceptsJson'
        -
          in: path
          name: employeeId
          required: true
          schema:
            type: integer
          description: 'Employee id'
      responses:
        '"200"':
          description: 'return today schedule'
          content:
            application/json:
              schema:
                type: array
                example: ['sample' : []]
        '"401"':
          description: 'Bearer token not authorized'
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Unauthenticated
  /employee/schedule/mass/:
    post:
      summary: 'mass create record'
      tags:
        - employeeschedule
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                employeeIds:
                  type: array
                schedule_type:
                  type: string
                  enum:
                    - REGULAR
                    - SPECIAL
                effective_date:
                  type: date
                schedule_id:
                  type: integer
                special_schedule_id:
                  type: integer
                type:
                  type: string
                  enum:
                    - PERMANENT
                    - ONE_TIME
              required:
                - employeeIds
                - schedule_type
                - effective_date
      security:
        -
          bearerAuth: {  }
      parameters:
        -
          $ref: '#/components/parameters/acceptsJson'
        -
          in: path
          name: employeeId
          required: true
          schema:
            type: integer
          description: 'Employee id'
      responses:
        '"201"':
          description: 'EmployeeSchedule created message'
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 'employee/schedule successfully created.'
        '"401"':
          description: 'Bearer token not authorized'
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Unauthenticated
