openapi: 3.0.0
info:
  title: 'HRMIS OTS API - Offense'
  version: 0.5.2
servers:
  -
    url: 'http://localhost:8088/api/'
    description: URI
components:
  parameters:
    acceptsJson:
      name: Accept
      in: header
      required: true
      schema:
        type: string
        example: application/json
        default: application/json
  examples:
    dummyuser:
      summary: 'Dummy username and password'
      value:
        username: dummyuser
        password: secret
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
tags:
  -
    name: offense
    description: 'Everything about Offense API'
paths:
  '/offense/parameter/':
    get:
      summary: 'get parameter'
      tags:
        - offense
      security:
        -
          bearerAuth: {  }
      parameters:
        -
          $ref: '#/components/parameters/acceptsJson'
      responses:
        '"200"':
          description: 'return parameters'
          content:
            application/json:
              schema:
                type: array
                example: ['sample' : []]
        '"401"':
          description: 'Bearer token not authorized'
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Unauthenticated
  /offense/create/{employeeId}:
    post:
      summary: 'create record'
      tags:
        - offense
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                recieved_date:
                  type: string
                type:
                  type: string
                offense:
                  type: string
                corrective_action_taken:
                  type: longText
                status:
                  type: string
                remarks:
                  type: string
                memo_date:
                  type: string
              required:
                - employee_id
                - recieved_date
                - type
                - offense
                - corrective_action_taken
                - status
                - memo_date
      security:
        -
          bearerAuth: {  }
      parameters:
        -
          $ref: '#/components/parameters/acceptsJson'
      responses:
        '"201"':
          description: 'Offense created message'
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 'offense successfully created.'
        '"401"':
          description: 'Bearer token not authorized'
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Unauthenticated
  '/offense/search/{employeeId}/{id}':
    get:
      summary: 'get record'
      tags:
        - offense
      security:
        -
          bearerAuth: {  }
      parameters:
        -
          $ref: '#/components/parameters/acceptsJson'
        -
          in: path
          name: id
          required: false
          schema:
            type: integer
          description: 'primary key'
        -
          in: query
          name: searchValue
          schema:
            type: string
          description: 'search value'
        -
          in: query
          name: page
          schema:
            type: integer
          description: 'for pagination'
        -
          in: query
          name: perPage
          schema:
            type: integer
          description: 'for pagination'
        -
          in: query
          name: field
          schema:
            type: string
          description: 'for sorting'
        -
          in: query
          name: order
          schema:
            type: string
            enum:
              - ASC
              - DESC
          description: 'for sorting'
      responses:
        '"200"':
          description: 'return Offense records'
          content:
            application/json:
              schema:
                type: array
                example:
                  -
                    id: 1
                    employee_id: relatedTo
                    recieved_date: string
                    type: string
                    offense: string
                    corrective_action_taken: longText
                    status: string
                    remarks: string
                    memo_date: string
                    created_at: '2021-08-27 10:23:09'
                    updated_at: '2021-08-27 10:23:09'
                  -
                    id: 1
                    employee_id: relatedTo
                    recieved_date: string
                    type: string
                    offense: string
                    corrective_action_taken: longText
                    status: string
                    remarks: string
                    memo_date: string
                    created_at: '2021-08-27 10:23:09'
                    updated_at: '2021-08-27 10:23:09'
        '"401"':
          description: 'Bearer token not authorized'
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Unauthenticated
  '/offense/update/{id}':
    put:
      summary: 'update record'
      tags:
        - offense
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                employee_id:
                  type: integer
                recieved_date:
                  type: string
                type:
                  type: string
                offense:
                  type: string
                corrective_action_taken:
                  type: longText
                status:
                  type: string
                remarks:
                  type: string
                memo_date:
                  type: string
              required:
                - employee_id
                - recieved_date
                - type
                - offense
                - corrective_action_taken
                - status
                - memo_date
      security:
        -
          bearerAuth: {  }
      parameters:
        -
          $ref: '#/components/parameters/acceptsJson'
        -
          in: path
          name: id
          required: true
          schema:
            type: integer
          description: 'primary key'
      responses:
        '"204"':
          description: 'Offense update message'
          content: null
        '"401"':
          description: 'Bearer token not authorized'
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Unauthenticated
  '/offense/delete/{id}':
    delete:
      summary: 'delete record'
      tags:
        - offense
      security:
        -
          bearerAuth: {  }
      parameters:
        -
          $ref: '#/components/parameters/acceptsJson'
        -
          in: path
          name: id
          required: true
          schema:
            type: integer
          description: 'primary key'
      responses:
        '"204"':
          description: 'Offense delete message'
          content: null
        '"401"':
          description: 'Bearer token not authorized'
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Unauthenticated
